dist: trusty
sudo: required
language: node_js

matrix:
  fast_finish: true
  include:
    - node_js: 12
      env: GETH=true
    - node_js: 12
      env: PACKAGES=true
    - node_js: 12
      env: INTEGRATION=true
    - node_js: 12
      env: COVERAGE=true
  allow_failures:
    - node_js: 12
      env: COVERAGE=true

install:
  - npm i -g truffle
  - truffle obtain --solc=0.5.8
  - truffle unbox metacoin --force
  - truffle compile

cache:
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules # globally installed stuff (i.e. lerna)
    - ~/.config/truffle/compilers
