dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull ethereum/client-go:latest
  - docker pull ethereum/solc:0.4.22
  - sudo add-apt-repository --yes ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install solc --allow-unauthenticated

env:
  - INTEGRATION=true
  - GETH=true
  - PACKAGES=true

matrix:
  fast_finish: true
  allow_failures:
    - env: GETH=true

install:
  - npm install -g lerna
  - npm install -g yarn
  - npm run bootstrap

script:
  - npm run ci
