name: Node CI

on:
  push:
    branches:
    # long-lived branches
    - master
    - develop
    - next

    # other targets
    - truffle-db

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [10.x, 12.x]
        env: [GETH=true, QUORUM=true, PACKAGES=true, INTEGRATION=true, COVERAGE=true]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn lerna
    - run: yarn bootstrap
    - run: ${{ matrix.env }} yarn ci
