name: Node CI

on:
  pull_request:
    branches:
    - develop
    
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        node-version: [8x, 10.x, 12.x]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn lerna
    - run: yarn bootstrap
    - run: npm i -g truffle
